### ISSUE TITLE
Argus 3 pro

### ISSUE THREAD

**Issue by Th0tti** [starkillerOG/reolink_aio#1]
Do you think battery powered cameras will be supported in Home Assistant in future versions?

**Comment by starkillerOG** [comment]
They might, but I do not own battery powered camera's and they will probablly need some diffrent handeling because they might not always be availabel.
I would need to try it out to figure out how hard it would be to support battery powered camera's.

At least it is not going to happen any time soon.
I have a lot of other features I need to support/improve first.
