### ISSUE TITLE
Wifi Strength

### ISSUE THREAD

**Issue by CrashM85** [starkillerOG/reolink_aio#26]
Hi, Do the wifi cameras allow you to query the current wifi strength and could that be exposed as a sensor entity to HA?

**Comment by starkillerOG** [comment]
@CrashM85 yes the signal strength can be queryed using `GetWifiSignal`, so yes it could be added as a sensor in HomeAssistant. Although the number will be between 0 and  255 which is a bit arbitrary, it is unfortunately not in dbm.

I will add it to my to do list of feature requests.
However since I have many things to implement, this may take quite some time before I get to it.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).

**Comment by starkillerOG** [comment]
This library now supports the wifi signal strength query with this commmit I made: https://github.com/starkillerOG/reolink_aio/commit/69097feb54d7a431480a24b8db03098ba98587fe

Soon I will add the nessesary code to Home Asssitant to add it as a sensor.

**Comment by CrashM85** [comment]
Thanks! Have a coffee on me.

**Comment by starkillerOG** [comment]
The wifi signal sensor will be available in HomeAssistant 2023.8 that will be released on August 2nd 2023.

Therefore I will close this issue now.

**Comment by CrashM85** [comment]
Hi, Got the update for HA and it appears the wifi signal is just always "1" on a RLC-410W

**Comment by starkillerOG** [comment]
Yes indeed, the number on my cam correspondends to the amount of wifi bars, 1 is probably a pretty bad signal
