### ISSUE TITLE
Get Sdcard/Hdd existance and size used

### ISSUE THREAD

**Issue by mnpg** [starkillerOG/reolink_aio#38]
Hi @StarKillerOG, i have a other idea to offer the information of the status of the SdCard or Hdd if exists and, if the case, his size used.
Through the command GetHddInfo, you get have the status and size used: 

* Here GetHddInfo returns ; 
```
jeedom@jeedom:~/rl-api $ ./rl-api22.sh GetHddInfo '{"channel":0}'
{
  "HddInfo": []
}
```
In that case, it's a good information for HA to know if there is no storage
**These is no SdCard or Hdd in the camera**

If it's a case that storage exists, here how to check the size used
* here GetHddInfo returns : 
```
jeedom@jeedom:~/rl-api $ ./rl-api29.sh GetHddInfo '{"channel":0}'
{
  "HddInfo": [
    {
      "capacity": 30462,
      "format": 1,
      "mount": 1,
      "number": 0,
      "size": 779,
      "storageType": 2
    }
  ]
}
```
In that case, if the field 'StorageType' is equal at 1 it's a a Hdd and 2 if it is a SdCard

To have the size used of the device, here the command : round(size*100/capacity)
In that example : round(779x100)/30462 -> 3%

**Comment by starkillerOG** [comment]
The HDD/SD card storage sensor will be available in HA 2024.3.0 once this PR is merged: https://github.com/home-assistant/core/pull/110961

It will show the % of storage that is in use.

The entity will only be added if a SD or HDD storage is available

It will go unavailable if the SD card or HDD is no longer accesible.

Since this is now implemented, I will close this issue.
