### ISSUE TITLE
RTSP to local file?

### ISSUE THREAD

**Issue by nicolasbrailo** [starkillerOG/reolink_aio#61]
@starkillerOG are you interested in a PR to save a recording from the rtsp of the camera to a local file? Here's an example using ffmpeg: https://github.com/nicolasbrailo/zigbee2mqtt2web/blob/master/zigbee2mqtt2web_extras/reolink_cam/rtsp.py

If you think it could fit as an extra utility in this repo, I can prepare a PR.

**Comment by starkillerOG** [comment]
I am trying to keep this library mainly focused on Home Assistant.
Therefore I don't want too many extra's that won't be used in HomeAssistant because they increase the maintenance burden.
(Which is already pretty high with about 70.000 HomeAssistant installs using this library).

Maybe you could create a seperate repo for addon-utilities that just uses reolink-aio as a dependency.
Something like "reolink_aio_utility"
How does that sound?
