### ISSUE TITLE
Password required, inability to bypass

### ISSUE THREAD

**Issue by Menethoran** [starkillerOG/reolink_aio#71]
**Describe the bug**
Integration requires password
**To Reproduce**
Steps to reproduce the behavior. Pleaee provide the error from the log if possible.
go to HA, attempt to add a new camera (or have one autodiscovered by HA and attempt to adopt device without a password
**Expected behavior**
Ability to adopt a camera without a password as the default state does not assign a password.
**Screenshots**
If you need more explanation, ill attach screen shotes.
**Environment:**
Please provide useful information about your environment, like:
 - Reolink NVR/camera model
 - NVR/camera firmware version

ANY reolink adoptable by Home Assistant

**Additional context**

We have had issues with people who had physical access to the cameras would factory reset them, knocking them out of config. so, we just adopt them all with factory settings and catch them in the act now.

**Comment by starkillerOG** [comment]
At this stage it is not possible to communicate with a uninitialized camera since the HTTP(S) port of a unintialized camera is in most cases closed so the API that the Reolink integration uses will not be available.
See this part of the documentation: https://www.home-assistant.io/integrations/reolink/#1-initializing-and-configuring-camera-credentials

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).
